```{r}
library(tidyverse)
library(janitor)


simulated_data <-
  tibble(
    # Use 1 through to 151 to represent each division
    "Division" = 1:151,
    # Randomly pick an option, with replacement, 151 times
    "Party" = sample(
      x = c("Liberal", "Labor", "National", "Green", "Other"),
      size = 151,
      replace = TRUE
    )
  )

write_csv(x=simulated_data, file="downlaoded_data.csv")
```


```{r}
#### Read in the data ####
raw_elections_data <-
  read_csv(
    file = 
      "https://www.elections.ca/res/rep/off/ovr2021app/53/data_donnees/table_tableau11.csv",
    show_col_types = FALSE
  )

# We have read the data from the AEC website. We may like to save
# it in case something happens or they move it.
write_csv(
  x = raw_elections_data,
  file = "canadian_votings.csv"
)
```

```{r}
# Make the names easier to type
cleaned_elections_data <-
  clean_names(raw_elections_data)

# Have a look at the first six rows
# head(cleaned_elections_data)

cleaned_elections_data <-
  cleaned_elections_data |>
  select(
    electoral_district_name_nom_de_circonscription,
    elected_candidate_candidat_elu
  )

# head(cleaned_elections_data)

cleaned_elections_data <-
  cleaned_elections_data |>
  rename(
    division = electoral_district_name_nom_de_circonscription,
    elected_party = elected_candidate_candidat_elu
  )

head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  separate(
    col = elected_party,
    into = c("Other", "party"),
    sep = "/"
  ) |>
select(-Other)
head(cleaned_elections_data)
```

```{r}
cleaned_elections_data$party |>
  unique()

head(cleaned_elections_data)

temp <-
  cleaned_elections_data |>
  mutate(
    party =
      case_match(
        party,
        "Libéral" ~ "Liberal",
        "Conservateur" ~ "Conservative",
        "Bloc Québécois" ~ "BQ",
        "NPD-Nouveau Parti démocratique" ~ "NDP",
        "Parti Vert" ~ "Greens"
      )
  )

head(temp)
```

```{r}
cleaned_elections_data |>
  count(party)

cleaned_elections_data |>
  ggplot(aes(x = party)) + # aes abbreviates "aesthetics" 
  geom_bar()

cleaned_elections_data |>
  ggplot(aes(x = party)) +
  geom_bar() +
  theme_minimal() + # Make the theme neater
  labs(x = "Party", y = "Number of seats") # Make labels more meaningful
```